# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '5期-百思不得姐' do
    pod "AFNetworking"
    pod "SDWebImage"
    pod "MJExtension"
    pod "SVProgressHUD"
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 5期-百思不得姐

  target '5期-百思不得姐Tests' do
    inherit! :search_paths

  end



end
