# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '5期-百思不得姐' do
    pod "AFNetworking"
    pod "SDWebImage"
    pod "MJExtension"
    pod "SVProgressHUD"
    pod "MJRefresh"
    pod "DACircularProgress"




end
